#!/usr/bin/python3.8
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from os import system, environ
import http.client
from time import sleep
import pickle

username_ = environ.get('royalRoadEmail')
password_ = environ.get('royalRoadPassword')
try:
    with open('/home/roshan/.myscripts/files/RoyalRoadUpdate','rb') as bookUpdateFile:
        stored_bookUpdateData = pickle.load(bookUpdateFile)
        fileNotFound = False
except FileNotFoundError:
    fileNotFound = True

driverPath = '/home/roshan/.chromedriver'

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.binary_location = '/usr/bin/vivaldi'

driver = webdriver.Chrome(driverPath, options = options)
loop_flag = True
while loop_flag:
    try:
        loop_flag1 = True
        while loop_flag1:
            print('Going to royalroad.com')
            driver.get('https://www.royalroad.com/my/follows')

            print('Signing In...')
            email = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "email")))
            email.send_keys(username_)

            password = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "password")))
            password.send_keys(password_)

            signin_button = driver.find_element(By.CSS_SELECTOR,'body > div > div.col-md-5.col-lg-4.col-xxl-3.align-self-center > div > form:nth-child(4) > button')
            signin_button.click()

            loop_flag1 = False
            print('Signed In')

        while True:
            fiction_list = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.CLASS_NAME, "fiction-list")))

            titles = fiction_list.find_elements(By.TAG_NAME,'h2')
            bookUpdateData = {}
            print('Reading book updated data...')
            for title in titles:
                try:
                    title_updated = title.find_element(By.TAG_NAME,'span')
                    bookUpdateData[title.text] = True
                except selenium.common.exceptions.NoSuchElementException:
                    bookUpdateData[title.text] = False
            print('Done')
            if fileNotFound:
                fileNotFound = False
                with open('/home/roshan/.myscripts/files/RoyalRoadUpdate','wb') as bookUpdateFile:
                    pickle.dump(bookUpdateData, bookUpdateFile)
                    stored_bookUpdateData = bookUpdateData
            elif bookUpdateData != stored_bookUpdateData:
                if bookUpdateData.keys() == stored_bookUpdateData.keys():
                    for i in bookUpdateData:
                        if bookUpdateData[i] and not stored_bookUpdateData[i]:
                            system(f"notify-send 'Royal Road Update' '{i}'")
                            with open('/home/roshan/.myscripts/files/RoyalRoadUpdate','wb') as bookUpdateFile:
                                pickle.dump(bookUpdateData, bookUpdateFile)
                                stored_bookUpdateData = bookUpdateData
                        elif bookUpdateData.keys() != stored_bookUpdateData.keys():
                            with open('/home/roshan/.myscripts/files/RoyalRoadUpdate','wb') as bookUpdateFile:
                                pickle.dump(bookUpdateData, bookUpdateFile)
                                stored_bookUpdateData = bookUpdateData

            sleep(60)
            driver.get(driver.current_url)
    except Exception:
        network_check = True
        print('Checking Network...')
        while network_check:
            try:
                conn = http.client.HTTPSConnection("8.8.8.8", timeout=5)
                conn.request("HEAD","/")
                network_check = False
            except Exception:
                sleep(5*60) 
